### ISSUE TITLE
Quick TODO before the site can be considered for release

### ISSUE THREAD

**Issue by thomas-mangin** [IXLeeds/marketingsite#1]
### index page
- [ ] remove all fill-up latin from pages
- [ ] replace static front page statistic by JS pulling a new backend service providing the data
- [ ] make sure all logo are hyperlink toward the right site
- [ ] update the peak data to be right
- [ ] facebook link is wrong
### Common to many pages
- [ ] what we do/feature is empty
### members.html
- [ ] have generate the right number
- [ ] add the right members
- [ ] statically first, and later generated this from the IXPManager DB
### about_us.html
- [ ] check the date, it says 2010, Andy says on the video 2011 - can not recall the right info
- [ ] facebook link is wrong
- [ ] Andy does not work for HE anymore ( logo and blurb )
### join.html
- [ ] we do accept Gb and 10Gb connections
- [ ] already connected : fluidata
### events.html
- [ ] All the event links are going to IXLeeds4 (need to back-fill every event)
- [ ] We will not be able to put the content in GitHub (for the video at least, perhaps the presentation will fit)
- [ ] keep the current links for content (so it is not on github and does not upset google)
# outreach.html
- [ ] write the content up and remove latin

**Comment by Nevmerzhitskaya** [comment]
Hello Thomas,

Please, send us the following additional information for this task:
1) access to server (ftp or sftp, user and password);
2) access to database (link to database, user and password);
3) actual information, video and images 

Thank you in advance and Merry Christmas!
